In [16]:
import time
from getting_accurate_solutions import *
from random import normalvariate as random_normalvariate
from auxiliary_functions_and_classes import minus
from gradient_descent import batch_gradient_descent


#______________Решение плохообусловленных матриц с помощью пакетного градиентного спуска_____________________

In [17]:
#______________________N=6________________________
start = time.time()
decision_6 = batch_gradient_descent(A_6, B_6, n_iterations=100000)
print(f'Время работы алгоритма = {time.time() - start}')
print(decision_6)

Время работы алгоритма = 0.7025952339172363
[[1.00497927]
 [2.00347525]
 [2.97946296]
 [4.01324892]
 [4.99821179]
 [5.9990852 ]]


In [18]:
print('Разница между точным решением и полученным:')
dec = minus(decision_6, the_exact_solution_6)
print(dec)
print('Норма L2 вектора разницы:')
print(np.linalg.norm(list(map(lambda x: x[0], dec))))

Разница между точным решением и полученным:
[[0.0049792676515221235], [0.0034752451080537483], [-0.020537038023014098], [0.013248921942054181], [-0.0017882076941795333], [-0.0009147970852581011]]
Норма L2 вектора разницы:
0.025262795545161608


In [19]:
#______________________N=10________________________
start = time.time()
decision_10 = batch_gradient_descent(A_10, B_10, n_iterations=100000)
print(f'Время работы алгоритма = {time.time() - start}')
print(decision_10)

Время работы алгоритма = 0.8553586006164551
[[1.00769807]
 [1.99433085]
 [3.00215522]
 [4.00116537]
 [4.99696609]
 [6.00307625]
 [6.99852102]
 [7.99863887]
 [9.00469699]
 [9.99275128]]


In [20]:
print('Разница между точным решением и полученным:')
dec = minus(decision_10, the_exact_solution_10)
print(dec)
print('Норма L2 вектора разницы:')
print(np.linalg.norm(list(map(lambda x: x[0], dec))))

Разница между точным решением и полученным:
[[0.007698026507565903], [-0.005669186992034225], [0.002155292074096593], [0.0011653573038943321], [-0.0030339182313925406], [0.003076256439679348], [-0.001478963880925832], [-0.0013612076482782953], [0.004697020026544152], [-0.007248675602077981]]
Норма L2 вектора разницы:
0.013954073379713088


In [21]:
#______________________N=15________________________
start = time.time()
decision_15 = batch_gradient_descent(A_15, B_15, n_iterations=100000, eta=0.08)
print(f'Время работы алгоритма = {time.time() - start}')
print(decision_15)

Время работы алгоритма = 1.1126503944396973
[[-2.05796161]
 [ 2.13787754]
 [-0.53860164]
 [ 7.10811761]
 [-1.13550849]
 [ 2.27569126]
 [ 2.02779774]
 [-2.39673491]
 [ 3.26086395]
 [ 1.2952121 ]
 [ 4.68934377]
 [-5.23193457]
 [ 4.97478393]
 [ 5.69115854]
 [ 1.27686414]]


In [22]:
print('Разница между точным решением и полученным:')
dec = minus(decision_15, the_exact_solution_15)
print(dec)
print('Норма L2 вектора разницы:')
print(np.linalg.norm(list(map(lambda x: x[0], dec))))

Разница между точным решением и полученным:
[[4.3648316072619764e-07], [-4.220432732182644e-07], [4.070729358041092e-07], [-3.503862737730401e-07], [2.2445611436161528e-07], [-2.7686142711758066e-08], [-2.1551215612092278e-07], [4.6413564858127643e-07], [-6.735986919359505e-07], [8.078393511912196e-07], [-8.488332179368285e-07], [8.024323978617076e-07], [-6.979517817029546e-07], [5.787750216867948e-07], [-4.851864552346541e-07]]
Норма L2 вектора разницы:
2.1209454875709263e-06
